### ISSUE TITLE
Screen not properly clears, after exiting.

### ISSUE THREAD

**Issue by Achaean** [jtsiomb/termtris#2]
Quitting the game, leaving garbage on screen (purple color everywhere and the bash prompt on the top-right corner) and you have to press Ctrl-L.

I'm on a Debian oldstable based distro and termtris build and installed properly.
G.

**Comment by jtsiomb** [comment]
Which terminal emulator are you using?

**Comment by Achaean** [comment]
Oh, you are right!
I tried it at the console (from inside the desktop).
Switching to a VT (with ctrl-aAlt-F1), I tried it again and works perfectly!

**Comment by jtsiomb** [comment]
Ok, this isn't very clear, so let me attempt to clarify what I think you're saying: running it under X with an X terminal emulator leaves the terminal dirty, but running it from a linux virtual terminal works properly?

Assuming I got it right, please let me know which terminal emulator you're using under X, where it fails to reset correctly on exit.

**Comment by Achaean** [comment]
Ooops! Sorry for failing to provide all the details!  :-)
Anyway, you got it right.

For terminal emulation,  (on top of X) I'm using Konsole (KDE's console).

**Comment by jtsiomb** [comment]
I managed to reproduce the problem with Konsole in a virtual machine. I'll try to see what can be done to fix it at some point. Until then I suggest using any other terminal emulator. I have tested xterm, rxvt, aterm, iterm2, Terminal.app, kermit, the windows 10 console, and the gnome terminal, and all of them work correctly.

**Comment by Achaean** [comment]
Not much of a problem (at my opinion).
Just a minor glitch.

As a workaround, one can play it on a VT or with a launcher.
If someone choose the later, at launcher's "Advanced Options", enable the "Run in terminal" option (in order the launcher to be functional) and (for aesthetic reasons) at "Terminal options" put the text between quotations¨"--hide-menubar --hide-tabbar" -> OK -> OK.

**Comment by jtsiomb** [comment]
I pushed some changes recently, which I think might have solved this issue. Can you try the latest release (1.8.2) or the latest code from git and let me know if it's fixed?

**Comment by Achaean** [comment]
Nice job!!!
Problem solved!

Μπράβο Γιάννη!
Ωραίος!!!  ;-)
