### ISSUE TITLE
In some occasions, termtris tries to set cursor to negative location

### ISSUE THREAD

**Issue by technomancer-lv** [jtsiomb/termtris#4]
In my case I'm running latest version of termtris on Linux. It's tested as working over SSH and direct serial connection.
The problem is with my vintage terminal setup. So, I have DECserver 200MC terminal server connected to my network and most of my vintage terminals are connected to this terminalserver. From the terminalserver I can connect to the Linux machine using LAT protocol and work on it. However, when trying to run termtris from this setup, it was not being displayed correctly on three different serial terminals (VT100, VT220 and HP). I tried VT220 using a direct connection and it works correctly. After some debugging I found out that when I'm using a terminalserver, for some reason termtris is trying to put cursor on negative locations. Some examples I noticed being sent to terminal:
esc[18;-19H
esc[2;-9H

I assume that termtris is trying to read a terminal screen size and for some reason using a terminalserver between computer and Linux machine messes up this parameter.

**Comment by jtsiomb** [comment]
I'm calling the TIOCGWINSZ ioctl to get the current terminal size on init, and then catch the SIGWINCH signal to detect changes to the terminal size afterwards. Maybe the kernel doesn't know the terminal size if it's over the terminal server and the ioctl fails, or returns 0?

I just added error checking to that ioctl and sanity check that the returned terminal size is not 0, and I'm falling back to a hardcoded 80x24 if it fails, can you test and see if that solves your issue?

**Comment by jtsiomb** [comment]
... also if it's not too much of a hassle, I'd love to see how termtris works on the various terminals you have. If you could shoot some photos and either post them here or somewhere else and post links, I'd appreciate it.

**Comment by technomancer-lv** [comment]
OK, I'll get the latest version and will try it out. Thanks!
I'll take some photos too. ;)

**Comment by technomancer-lv** [comment]
I can confirm that it works perfectly now.

**Comment by technomancer-lv** [comment]
![IMG_20231019_192428](https://github.com/jtsiomb/termtris/assets/49709192/d30087a7-3377-466e-9886-9d8c082cb39c)
![IMG_20231019_185330](https://github.com/jtsiomb/termtris/assets/49709192/bf1ffce5-a052-47dd-9be5-56421fac0f34)
![IMG_20231019_185531](https://github.com/jtsiomb/termtris/assets/49709192/b061a388-32a1-422c-8bbf-16c51b170f0d)
![Uploading IMG_20231019_201925.jpg…]()

**Comment by technomancer-lv** [comment]
![Uploading IMG_20231019_201925.jpg…]()

**Comment by jtsiomb** [comment]
Perfect. Thank you for the pics, much appreciated. I think I'll make a gallery on the termtris website. If you feel like trying (and possibly photographing) one more thing. The VT-220 is theoretically one of the terminals for which I've included support for custom soft-fonts for the tetris bricks. It's not the same 3D bevelled bricks as I've done for the VT320 and above, because the VT220 apparently can't make adjacent glyphs gapless, so I just made it a simple line drawing thing, but I've never seen it on a real VT220 if it really works. Can you run with `-g` to enable the graphical bricks on the VT220 and report (or send a pic of) the result?

**Comment by jtsiomb** [comment]
Also I noticed the VT100 doesn't support hiding the cursor apparently, so I just commited a small change to move it out of the way after every update, to make it less annoying.

**Comment by technomancer-lv** [comment]
Yes, no problem with that. I'll try out the font load on VT220 later today.
