### ISSUE TITLE
how to use soft fonts?

### ISSUE THREAD

**Issue by echo2go** [jtsiomb/termtris#6]
I have tried to use softfonts for Termtris, but without success.

I have used Mintty (Cygwin - https://mintty.github.io/ - https://github.com/mintty/mintty), Contour (https://github.com/contour-terminal/contour) and XFCE-Terminal as terminal.

I'm not sure if these support softfonts at all. Maybe you can suggest a terminal that uses this feature?
Or maybe you can add Sixel support for your Termtris? This should be more common than softfonts

**Comment by j4james** [comment]
These are the terminals I know of that support soft fonts:

- KoalaTerm
- MLTerm
- PowerTerm
- Reflection Desktop
- RLogin
- Windows Terminal

Windows Terminal is the only one I've actually tested with termtris (running under WSL), but the others should work in theory. However, you may first need to set your `TERM` environment variable to something like `vt320` or `vt420`, otherwise termtris can hang at startup. Also note that some terminals will probably only work with one of those `TERM` values, so try them both.

**Comment by echo2go** [comment]
many thanks. I will look for one of the terminals and test it. :o)

I installed MLTerm because it was in my distribution repo. The other terminals aren't.
Unfortunately, the result is not as expected. After starting termtris the game only appears in black and white and some gray dots for the frame. Square brackets are not shown. 
It makes no difference whether I export vt320 or vt420 into the TERM variable.

It seems to me, that the other terminal in your list are for windows?

**Comment by jtsiomb** [comment]
The softfont feature uses the DECDLD command (https://vt100.net/docs/vt220-rm/chapter4.html#S4.16), which was supported by DEC terminals from VT2x0 series and upwards, and some 3rd party terminals with various levels of compatibility. Other than the new windows terminal, I'm not aware of any other terminal emulator which supports that feature.

MAME, the arcade machine emulator can emulate a VT240. You can use that to test the feature if you like. I have this in a script for running MAME in VT240 mode: `mame -biospath ~/mame/roms -window -nomouse -vol -15 vt240 -host pty`
Then you need to enter the MAME configuration menu, see which pseudoterminal it allocated, and spawn a getty on that. You'll also need the VT240 ROMs (see `-biospath` option above), which you should be able to find floating around the web. Let me know if you're unable to locate them and I'll try to upload them somewhere.

**Comment by jtsiomb** [comment]
The reason you need to have the correct TERM declared, is that the DEC down-line loadable soft-font feature works in a different way in VT2x0 terminals, VT3x0 terminals, and VT4x0 and above. So termtris needs to know which softfont to load. The windows terminal supports all three, and you can try them all to see the differences.

**Comment by echo2go** [comment]
Thank you very much.

I switched to Windows and started the Windows Terminal with Cygwin Backend.
After setting "export TERM=vt320" I could actually see termtris with the graphics/soft font.

It's a pity that I can't get it to work under Linux. I'll try out my old VT520 later :o)

What about XTERM? This is a feature rich terminal. Can it handle soft fonts?

**Comment by j4james** [comment]
@echo2go I think you should be able to get it to work in [MLTerm](https://github.com/arakiken/mlterm) with the following patch (it only seems to accept `DECDLD` sequences when the _Pcss_ parameter is included):

```patch
diff --git a/src/ansi.c b/src/ansi.c
index d60af8f..1d353a3 100644
--- a/src/ansi.c
+++ b/src/ansi.c
@@ -169,13 +169,13 @@ void ansi_init(void)
 				break;
 			case 63:
 				/* VT320 mode, 15x12 */
-				printf("\033P1;%d;1;15;0;2;12{ @%s\033\\", (int)custom_char[i] - 32,
+				printf("\033P1;%d;1;15;0;2;12;0{ @%s\033\\", (int)custom_char[i] - 32,
 						sixels15x12[i]);
 				break;
 			case 64:
 			default:
 				/* VT420 mode, 10x16 */
-				printf("\033P1;%d;1;10;0;2;16{ @%s\033\\", (int)custom_char[i] - 32,
+				printf("\033P1;%d;1;10;0;2;16;0{ @%s\033\\", (int)custom_char[i] - 32,
 						sixels10x16[i]);
 			}
 		}
```

> What about XTERM? This is a feature rich terminal. Can it handle soft fonts?

Nope. Quoting the [man page](https://invisible-island.net/xterm/manpage/xterm.html#h2-EMULATIONS): "VT220 emulation does not support soft fonts".

**Comment by jtsiomb** [comment]
Thanks for the suggestion, indeed by specifying the default value to Pcss fixes the softfont download issue in mlterm.

**Comment by jtsiomb** [comment]
Also it looks like with mlterm there's no need to change TERM (other than to force a specific softfont), because it sends a device attribute string which advertises support for softfonts, and termtris detects that automatically.

**Comment by echo2go** [comment]
> @echo2go I think you should be able to get it to work in [MLTerm](https://github.com/arakiken/mlterm) with the following patch (it only seems to accept `DECDLD` sequences when the _Pcss_ parameter is included):
> 
> ```diff
> diff --git a/src/ansi.c b/src/ansi.c
> index d60af8f..1d353a3 100644
> --- a/src/ansi.c
> +++ b/src/ansi.c
> @@ -169,13 +169,13 @@ void ansi_init(void)
>  				break;
>  			case 63:
>  				/* VT320 mode, 15x12 */
> -				printf("\033P1;%d;1;15;0;2;12{ @%s\033\\", (int)custom_char[i] - 32,
> +				printf("\033P1;%d;1;15;0;2;12;0{ @%s\033\\", (int)custom_char[i] - 32,
>  						sixels15x12[i]);
>  				break;
>  			case 64:
>  			default:
>  				/* VT420 mode, 10x16 */
> -				printf("\033P1;%d;1;10;0;2;16{ @%s\033\\", (int)custom_char[i] - 32,
> +				printf("\033P1;%d;1;10;0;2;16;0{ @%s\033\\", (int)custom_char[i] - 32,
>  						sixels10x16[i]);
>  			}
>  		}
> ```


I wanted to use your patch, but I did not find the file "ansi.c" in the mlterm sources. Which file should I apply this patch to?

**Comment by jtsiomb** [comment]
These changes are for termtris, not mlterm, and I've already applied them in the last commit.

**Comment by echo2go** [comment]
Many thanks for your support.
After patching termtris it worked with mlterm perfectly.
It also worked on my old vt520 but only in black and white due to the tube
